#!/usr/bin/env ti-guile
!#

(add-to-load-path "lib")

;; Load ubu module.
(use-modules (ubu))
(use-modules (ubu-lib path))
(use-modules (ubu-lib adoc))


;; User help.
(action-help
 ""
 "  Build utility for: ubu install"
 ""
 "    Usage:"
 "      ubu <opts-and-cmds>"
 ""
 "    Actions:"
 "      help            This help."
 "      install         Install ubu to $GUILE_LOAD_PATH and $HOME/usr/man"
 ""
 ""
 "  Copyright (c) 2020, Tero Isannainen"
 "")

;; Setup install variables.
(set "adoc-prog-name" "ubu")

;; By default install ubu.

(action install
 (sh "cp lib/ubu.scm" (get "user-install-path"))
 (adoc-build-man)
 (adoc-install-man))
(ubu-default "install")

(action test
        (with-output
         (in-dir "test"
                 (sh "test-ubu"))))

(action install-ubu-lib
        (let* ((ubu-lib-dir (cat (get "user-install-path") "/ubu-lib")))
          (sh "cp -r ubu-lib/*.scm" ubu-lib-dir)
          (sh "cp ubu-lib/inotify/inotify.scm" ubu-lib-dir)))

(action clean
        (sh "rm -f" (get "doc-dst")))

(ubu-run-cli)
